"""adiciona tabelas compras_cartao e parcelas_cartao

Revision ID: 2ed2e35cd593
Revises: b2c9e8afc70a
Create Date: 2026-04-14 02:51:52.635289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed2e35cd593'
down_revision = 'b2c9e8afc70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compras_cartao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('parcelas', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.Enum('alimentacao', 'transporte', 'lazer', 'moradia', 'outros', name='categoria_compra_enum'), nullable=False),
    sa.Column('data_compra', sa.Date(), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcelas_cartao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('valor_parcela', sa.Float(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('paga', sa.Boolean(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compras_cartao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcelas_cartao')
    op.drop_table('compras_cartao')
    # ### end Alembic commands ###
