"""Adiciona campo tipo na tabela despesas

Revision ID: 2fbd1645151a
Revises: 37c5dca14e96
Create Date: 2026-03-03 18:45:06.413120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbd1645151a'
down_revision = '37c5dca14e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.Enum('fixa', 'variavel', name='tipo_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
