"""Adiciona tabela Orcamento

Revision ID: 37c5dca14e96
Revises: 7e55c9f203fe
Create Date: 2025-10-12 02:54:46.558527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c5dca14e96'
down_revision = '7e55c9f203fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.String(length=7), nullable=False),
    sa.Column('valor_orcamento', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orcamentos')
    # ### end Alembic commands ###
