"""adiciona tipo parcelado e parcela_id em despesas

Revision ID: 518b05bc5252
Revises: 2ed2e35cd593
Create Date: 2026-05-21 02:19:35.226193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518b05bc5252'
down_revision = '2ed2e35cd593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE despesas MODIFY tipo ENUM('fixa','variavel','parcelado') NOT NULL")

    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parcela_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'parcelas_cartao', ['parcela_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parcela_id')

    # ### end Alembic commands ###
