"""adiciona tabela recorrencias

Revision ID: b2c9e8afc70a
Revises: 2fbd1645151a
Create Date: 2026-03-28 19:24:21.871307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c9e8afc70a'
down_revision = '2fbd1645151a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recorrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frequencia', sa.Enum('semanal', 'mensal', 'anual', name='frequencia_enum'), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('despesa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['despesa_id'], ['despesas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recorrencias')
    # ### end Alembic commands ###
