"""adiciona tabelas metas e historico_metas

Revision ID: d67889a85df9
Revises: 518b05bc5252
Create Date: 2026-06-01 23:00:22.826838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67889a85df9'
down_revision = '518b05bc5252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('valor_objetivo', sa.Float(), nullable=False),
    sa.Column('valor_acumulado', sa.Float(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_prazo', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ativa', 'concluida', 'cancelada', name='status_meta_enum'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['metas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_metas')
    op.drop_table('metas')
    # ### end Alembic commands ###
